### ISSUE TITLE
reading github.com/xtaci/smux/go.mod at revision v2.1.0: unknown revision v2.1.0

### ISSUE THREAD

**Issue by espeed** [aperturerobotics/bifrost#168]
go install -v
go: downloading github.com/urfave/cli/v2 v2.27.0
go: downloading github.com/aperturerobotics/starpc v0.22.5-0.20231227005941-f9649d8c2a3d
go: downloading golang.org/x/exp v0.0.0-20231226003508-02704c960a9b
go: downloading github.com/xtaci/smux/v2 v2.1.0
get "golang.org/x/exp": found meta tag vcs.metaImport{Prefix:"golang.org/x/exp", VCS:"git", RepoRoot:"https://go.googlesource.com/exp"} at //golang.org/x/exp?go-get=1
../../transport/common/kcp/link.go:24:2: reading github.com/xtaci/smux/go.mod at revision v2.1.0: unknown revision v2.1.0

go version
go version go1.21.5 linux/amd64

**Comment by paralin** [comment]
Fixed. I had that version cached locally. Not sure what happened but it seems they retracted the v2.x version.

**Comment by espeed** [comment]
Now it's giving...

go install -v
runtime/internal/sys
# runtime/internal/sys
/usr/lib/golang/src/runtime/internal/sys/intrinsics_common.go:9:7: len8tab redeclared in this block
	/usr/lib/golang/src/runtime/internal/sys/intrinsics.go:76:7: other declaration of len8tab
/usr/lib/golang/src/runtime/internal/sys/intrinsics_common.go:32:6: Len64 redeclared in this block
	/usr/lib/golang/src/runtime/internal/sys/intrinsics.go:99:6: other declaration of Len64
/usr/lib/golang/src/runtime/internal/sys/intrinsics_common.go:50:7: m0 redeclared in this block
	/usr/lib/golang/src/runtime/internal/sys/intrinsics.go:117:7: other declaration of m0
/usr/lib/golang/src/runtime/internal/sys/intrinsics_common.go:51:7: m1 redeclared in this block
	/usr/lib/golang/src/runtime/internal/sys/intrinsics.go:118:7: other declaration of m1
/usr/lib/golang/src/runtime/internal/sys/intrinsics_common.go:52:7: m2 redeclared in this block
	/usr/lib/golang/src/runtime/internal/sys/intrinsics.go:119:7: other declaration of m2
/usr/lib/golang/src/runtime/internal/sys/intrinsics_common.go:55:6: OnesCount64 redeclared in this block
	/usr/lib/golang/src/runtime/internal/sys/intrinsics.go:122:6: other declaration of OnesCount64
/usr/lib/golang/src/runtime/internal/sys/intrinsics_common.go:86:6: LeadingZeros64 redeclared in this block
	/usr/lib/golang/src/runtime/internal/sys/intrinsics.go:153:6: other declaration of LeadingZeros64
/usr/lib/golang/src/runtime/internal/sys/intrinsics_common.go:89:6: LeadingZeros8 redeclared in this block
	/usr/lib/golang/src/runtime/internal/sys/intrinsics.go:156:6: other declaration of LeadingZeros8
/usr/lib/golang/src/runtime/internal/sys/intrinsics_common.go:92:6: Len8 redeclared in this block
	/usr/lib/golang/src/runtime/internal/sys/intrinsics.go:159:6: other declaration of Len8
/usr/lib/golang/src/runtime/internal/sys/intrinsics_common.go:101:6: Prefetch redeclared in this block
	/usr/lib/golang/src/runtime/internal/sys/intrinsics.go:200:6: other declaration of Prefetch
/usr/lib/golang/src/runtime/internal/sys/intrinsics_common.go:101:6: too many errors

**Comment by espeed** [comment]
However, your update works on my Mac M1 running Fedora 39, but not my Xeon running Fedora 39. Will look into this more.

**Comment by paralin** [comment]
@espeed That looks like an issue with your Go installation,

make sure that "GOROOT" is not set in your environment.

**Comment by espeed** [comment]
unset GOSUMDB
unset GO111MODULE

fixed it. Set those when debugging the last issue.
