### ISSUE TITLE
transport: http3 WebTransport

### ISSUE THREAD

**Issue by gedw99** [aperturerobotics/bifrost#5]
https://github.com/adriancable/webtransport-go

https://github.com/ShimmerGuest/go-webtransport

**Comment by paralin** [comment]
https://github.com/aperturerobotics/bifrost/blob/master/transport/websocket/websocket.go#L90

**Comment by paralin** [comment]
I think these libraries will need to be a bit more mature & WebTransport supported more places before it will be better than just using Bifrost with Quic over Websocket

**Comment by gedw99** [comment]
Your right . Just wanted to let you know it exists as many others are wanting to use it

**Comment by paralin** [comment]
It definitely looks useful for implementing unreliable streams.

**Comment by gedw99** [comment]
yes agree about reliability.   

As i am sure you know, for browsers, WebTransport is supported but behind a flag.  It's just a matter of time until its turned on for all browsers.   

Until then "quic over websockets" is only way to go.  But once some browsers start to turn it on without the flag, your stack will be able to detect it and use WebTransport for that specific client.    That's the great thing about your multi protocol stack.

**Comment by paralin** [comment]
https://github.com/aperturerobotics/bifrost/tree/master/examples/websocket-browser-link

![image](https://user-images.githubusercontent.com/534887/156690507-6419a430-64b5-480c-bf70-6ef6aa0b4dce.png)

Example of running quic-over-websocket.

**Comment by gedw99** [comment]
sweet !!!

**Comment by paralin** [comment]
@gedw99 I'll reopen and just keep this as a discussion about WebTransport and implementing it in Bifrost eventually.

**Comment by gedw99** [comment]
Actually i have benchmarked flatbuffers and its not create for streaming pipes.

**Comment by gedw99** [comment]
i think we can close this ? Web transport is in...

**Comment by paralin** [comment]
I'll add it to Bifrost as a transport soon!

**Comment by paralin** [comment]
Now that WebRTC is merged I'll start looking at WebTransport.

**Comment by paralin** [comment]
WebTransport is not widely supported at the moment.

https://github.com/quic-go/webtransport-go

This is marked as "unfunded" and not maintained.

Once it becomes widely supported, I will reopen this issue! 👍🏽
