### ISSUE TITLE
example client ?

### ISSUE THREAD

**Issue by gedw99** [aperturerobotics/bifrost#6]
Would be good to have a basic example to exercise the code.

very intrigued to see how the entity graph performs.

Some golang frameworks i use to do this type of things

GIO - https://github.com/gioui/gio
- has a nice root component: https://github.com/gioui/gio-example/tree/main/component
- has a nice tree to represent the entity graph.
- has a data table and form for representing the properties of a graph node.
- has a gampad component. Nice way to play with real thing, instead of keyboard, mouse.

bubbletea -https://github.com/charmbracelet/bubbletea

**Comment by paralin** [comment]
There are some examples under examples/

I have other internal repos implementing both UI and TUI, not released yet.

If you want to take a crack at making an example client, please go ahead!

**Comment by paralin** [comment]
I've reformatted the examples/ tree to be a lot clearer now.

**Comment by gedw99** [comment]
> UI



> There are some examples under examples/
> 
> I have other internal repos implementing both UI and TUI, not released yet.

Will wait to see your examples... will be a good guide..

> 
> If you want to take a crack at making an example client, please go ahead!

**Comment by gedw99** [comment]
> I've reformatted the examples/ tree to be a lot clearer now.

thanks . will check it out.

**Comment by gedw99** [comment]
For  UI and TUI what frameworks are you using ? I can then try out extending on top.

I have not had time to add a gioui example but am planning to . Been too busy with work.

**Comment by paralin** [comment]
UI - react
TUI - bubble tea.

No worries. Will close this one for now.
