### ISSUE TITLE
make examples/websocket-browser-link easier to run 

### ISSUE THREAD

**Issue by gedw99** [aperturerobotics/bifrost#9]
This works without python for me ... its just using go install github.com/hajimehoshi/wasmserve@latest instead.

makefile:
```

BIT_EX_BROWSER_FSPATH=examples/websocket-browser-link
GO_ROOT=$(shell echo $(GOROOT))

bit-ex-websocket-run-socketserver:
	# works
	echo $(GO_ROOT)
	# boot websocket server
	cd $(BIT_EX_BROWSER_FSPATH)/server && go run .
	# listening for http/ws on address: :2015 

bit-ex-websocket-run-browser:
	cd $(BIT_EX_BROWSER_FSPATH)/browser && cp $(GO_ROOT)/misc/wasm/wasm_exec.js ./wasm_exec.js
	cd $(BIT_EX_BROWSER_FSPATH)/browser && GOOS=js GOARCH=wasm go build -o example.wasm -v ./
	go install github.com/hajimehoshi/wasmserve@latest
	cd $(BIT_EX_BROWSER_FSPATH)/browser && wasmserve .
	# Listening on: http://localhost:8080/
```

There is a bug with reconnections, but i am still getting to grips with the code. LOts of abstractions...

**Comment by paralin** [comment]
@gedw99 thanks, fixed. added a makefile target for wasmserve

**Comment by paralin** [comment]
@gedw99 FYI the "reconnect issue" you mentioned before has been fixed on master. The latest version of bifrost uses a much improved controllerbus implementation.

**Comment by gedw99** [comment]
Thanks @paralin will pull latest.

btw nats.go is able to run as WASM in web browsers now. A few projects are using it this way with good perf / stability. It uses websockets under the hood when running as WASM.

Is this useful for BitFrost ?  I would like to explore using  BitFrost in this way.

**Comment by paralin** [comment]
@gedw99 that's already implemented and there's an example of it under examples/

**Comment by gedw99** [comment]
https://github.com/aperturerobotics/bifrost/tree/master/examples/websocket-browser-link is the one you mean ?

**Comment by paralin** [comment]
Yes, I realize that nats isn't in that specific demo, but you can just load & run the nats controllers and it works fine in the browser.

**Comment by gedw99** [comment]
When you say “ load and run the nats controllers “, I can’t see how or where I can do that.

**Comment by paralin** [comment]
@gedw99 I added it to the example: https://github.com/aperturerobotics/bifrost/blob/master/examples/websocket-browser-link/common/common.go#L89

**Comment by gedw99** [comment]
Thanks. Will try it out …

**Comment by paralin** [comment]
@gedw99 Did some adjustments & I have the pubsub example working now, sending a message via NATS from the browser to the server over the websocket:

![image](https://user-images.githubusercontent.com/534887/209786106-a40fb1ad-19bb-4b42-9513-466afa651391.png)

As you can see, the message "hello from the browser" is authenticated and received correctly (with a signature from the browsers' peer ID).

**Comment by gedw99** [comment]
@paralin That’s awesome. 

I will try to reproduce using the notes in the rest of this issue. 

If you feel like it , please add reproduction notes to a Readme / makefile . Just a suggestion to make ut easier for others to try this out .

**Comment by paralin** [comment]
@gedw99 there is a readme in that example folder which explains how to run it.

**Comment by gedw99** [comment]
Ok thanks !
